### ISSUE TITLE
图片审核

### ISSUE THREAD

**Issue by davidelectricfree** [pcrbot/SetuScore#8]
请教一下，如果要把这个程序作为图片审核，只要发图就后台评分，凡是被定义为色图的就撤回消息，现在这个程序是使用了关键词作为触发，如果想达成我说的这种效果，应该用@sv.on_prefix 什么呢？对nonebot不太熟悉

**Comment by HMScygnet** [comment]
@sv.on_message('group')

**Comment by davidelectricfree** [comment]
> @sv.on_message('group')

好的谢谢，我试试
